config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: %i[show edit update] do
    get :menus, on: :collection
    get :favorite_recipes, on: :collection
    get :update_servings_for
  end

  resources :recipes do
    resource :favorite_recipes, only: %i[create destroy]
  end
  resources :categories # index, create
  resources :units
  resources :ingredients
  resources :user_ingredients
  resources :menus, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :user_ingredients,   dependent: :destroy

  # 該当なしの場合、作成してidを返すか,nilを返すか選択
  def self.get_id(name, new_create = false)
    ingredient = Ingredient.find_by(name: name)

    if ingredient.nil? && new_create
      ingredient = Ingredient.new(name: name)
      ingredient.save
    end
    ingredient.id
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :recipe_procedures,  dependent: :destroy
  has_many :recipe_ingredients, dependent: :destroy
  has_many :menu,               dependent: :destroy
  has_many :favorite_recipes,   dependent: :destroy

  accepts_nested_attributes_for :recipe_procedures,  allow_destroy: true
  accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true

  attachment :image

  # validations
  validates :title,  presence: true, length: { maximum: 10 }

  # TODO: 要テスト
  def self.get_ranking_from(from = Time.local(2000))
    Recipe.find(FavoriteRecipe.group(:recipe_id).where('created_at >= ?', from)
      .order('count(recipe_id) desc').limit(10).pluck(:recipe_id))
  end

  def favorited_by?(user)
    favorite_recipes.where(user_id: user.id).exists?
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  attr_accessor :name

  belongs_to :recipe
  belongs_to :ingredient
  belongs_to :unit
end

app/models/recipe_procedure.rb
class RecipeProcedure < ApplicationRecord
  belongs_to :recipe

  attachment :image
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :user_ingredients,   dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validation
  validates :name, presence: true, length: { maximum: 8 }
  has_many :recipes, dependent: :destroy
  has_many :recipes,          dependent: :destroy
  has_many :user_ingredients, dependent: :destroy
  has_many :menus,            dependent: :destroy
  has_many :favorite_recipes, dependent: :destroy
  has_many :recipes_through_favorite, through: :favorite_recipes, source: :recipe

  # validations
  validates :name, presence: true, uniqueness: true, length: { in: 3..8 }
  validates :servings_for,  presence: true,
                            numericality: {
                              only_integer: true,
                              greater_than_or_equal_to: 1
                            }
end

app/models/user_ingredient.rb
class UserIngredient < ApplicationRecord
  attr_accessor :name

  belongs_to :user
  belongs_to :ingredient
  belongs_to :unit
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.includes(:recipes)
                          .sort { |a, b| b.recipes.size <=> a.recipes.size }
    # TODO: ランキング表示
    @weekly_recipes  = Recipe.get_ranking_from(Time.current.beginning_of_week)
    @monthly_recipes = Recipe.get_ranking_from(Time.current.beginning_of_month)
    @total_recipes   = Recipe.get_ranking_from
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def create
    menu = current_user.menus.build(menu_params)
    menu.save!
    redirect_back(fallback_location: root_path)
  end

  def destroy
    # current_user.favorite_recipes.find_by(recipe_id: params[:recipe_id]).destroy!
    redirect_back(fallback_location: root_path)
  end

  private

  def menu_params
    params.require(:menu).permit(:servings_for, :recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
    @categories = Category.all
    @units = Unit.all
    recipe_procedures = @recipe.recipe_procedures.build
    recipe_ingredients = @recipe.recipe_ingredients.build
    # TODO: 下書き機能実装
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    # 既存の材料idか、新規作成して材料idを設定する
    @recipe.recipe_ingredients.each do |ingredient|
      ingredient.ingredient_id = Ingredient.get_id(ingredient.name, true)
    end

    if @recipe.save
      redirect_to recipes_path, success: '投稿に成功しました！'
    else
      @categories = Category.all
      @units = Unit.all
      render 'new'
    end
  end

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @menu = current_user.menus.build
  end

  private
  
  def recipe_params
    params.require(:recipe).permit(
      :title, :image, :description, :cooking_time, :servings_for, :public_view, :category_id,
      recipe_procedures_attributes: %i[id instruction image _destroy],
      recipe_ingredients_attributes: %i[id quantity gram ingredient_id unit_id _destroy name]
    )
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def create
    @unit = Unit.new(unit_params)
    @unit.save
    redirect_to ingredients_path
  end

  private

  def unit_params
    params.require(:unit).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes/_ranking.html.erb
<ul class="recipe-list">
  <% recipes.each.with_index(1) do |recipe, rank| %>
    <li class="li-item">
      <div class="li-rank"><%= rank %></div>
      <figure class="li-img-area"><%= attachment_image_tag recipe, :image %></figure>
      <div class="li-content">
        <p class="li-title"><%= recipe.title %></p>
        <p class="li-description"><%= recipe.description %></p>
      </div>
    </li>
  <% end %>
</ul>

app/views/recipes/_recipe_ingredients_fields.html.erb
<table class="table table-striped table-bordered ingredient-table">
  <tbody>
    <tr>
      <th>材料・調味料</th>
      <th>分量</th>
      <th>単位</th>
      <th></th>
    </tr>
    <%= f.nested_fields_for :recipe_ingredients, wrapper_tag: :tr do |recipe_ingredient| %>
      <%#= recipe_ingredient.hidden_field :ingredient_id %>
      <td class="td-name">
        <%= recipe_ingredient.text_field :name, class: 'form-control' %></td>
      <td class="td-quantity">
        <%= recipe_ingredient.text_field :quantity, class: 'form-control' %></td>
      <td class="td-unit">
        <%= recipe_ingredient.collection_select :unit_id, @units, :id, :name,
            {prompt: false}, {class: "form-control"} %>
        <%#= recipe_ingredient.number_field :gram,     class: 'form-control' %></td>
      <td class="td-delete">
        <%= recipe_ingredient.remove_nested_fields_link '×', class: 'btn btn-outline-danger', role: 'button' %></td>
    <% end %>
  </tbody>
</table>
<%= f.add_nested_fields_link :recipe_ingredients, '追加', class: 'btn btn-primary', role: 'button' %>

app/views/recipes/_recipe_procedures_fields.html.erb
<table class="table table-striped table-bordered procedure-table">
  <tbody>
    <tr>
       <th>手順</th>
       <th>写真</th>
       <th></th>
    </tr>
    <%= f.nested_fields_for :recipe_procedures, wrapper_tag: :tr do |procedure| %>
      <td><%= procedure.text_area   :instruction,     class: 'form-control' %></td>
      <td>
        <%= procedure.label :image, class: 'procedure-image-label' do %>
          <div class="procedure-img-box">
            <%= attachment_image_tag procedure.object, :image if procedure.object.image %>
            <img class="preview-procedure-image" >
          </div>
        <% end %>
        <%= procedure.file_field   :image, class: 'form-control' %>
      </td>
      <td class="td-delete"><%= procedure.remove_nested_fields_link '×', class: 'btn btn-outline-danger', role: 'button' %></td>
    <% end %>
  </tbody>
</table>
<%= f.add_nested_fields_link :recipe_procedures, '追加', class: 'btn btn-primary', role: 'button' %>

<script>
  $(document).on('change', 'input[type=file]', function (e) {
    var str = $(this).siblings('.procedure-image-label');
    var reader = new FileReader();

    reader.onload = function (e) {
        $(str).find('.preview-procedure-image').attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
  });
</script>

app/views/recipes/index.html.erb
<div class="recipe-index">
  <h2>レシピ一覧</h2>
  <div class="row row-cols-1 row-cols-md-3 recipe-table">
    <table class="table">
  <% @recipes.each do |recipe| %>
    <tr>
      <td class="row">
        <div class="col-md-4 recipe-img">
          <%= attachment_image_tag recipe, :image %>

        </div>
        <div class="col-md-8 recipe-info">
          <div class="title">
            <%= link_to recipe.title, recipe_path(recipe) %>
          </div>
          <div class="description">
            <%= recipe.description %>
          </div>
          <div class="details">
            <%= "#{recipe.user.name}  /  調理時間 #{recipe.cooking_time.to_s} 分" %>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
</table>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="recipe-new rounded">
  <h2>レシピ作成</h2>
  <% if @recipe.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <hr>
  <%= form_for @recipe do |recipe| %>
    <div class="row">
      <div class="col-sm-5">
        <div class="form-group">

          <div class="title-field field">
            <%= recipe.label :title, "タイトル" %><br />
            <%= recipe.text_field :title, class: 'form-control' %>
          </div>

          <div class="description-field field">
            <%= recipe.label :description, "説明" %><br />
            <%= recipe.text_area :description, class: 'form-control' %><br />
          </div>

          <div class="category-field field">
            <%= recipe.label :category_id, "カテゴリー" %><br />
            <%= recipe.collection_select :category_id, @categories, :id, :name,
                {prompt: false}, {class: "form-control"} %>
          </div>

          <div class="cooking-time-field field">
            <%= recipe.label :cooking_time, "調理時間（分）" %><br />
            <%= recipe.number_field :cooking_time, class: 'form-control' %>
          </div>

          <div class="image-field field">
            <%= recipe.label :image, "料理の写真" %><br />
            <label class="image-label" for="recipe-image">
              <div class="img-box">
                <img class="preview-recipe-image" >
              </div>
            </label>
            <%= recipe.file_field :image, id: 'recipe-image'%>
          </div>

        </div>
      </div>
      <div class="form-group col-sm-7">
        <div class="form-inline servings-for-form">
          <%= recipe.text_field :servings_for, value: current_user.servings_for, class: 'form-control' %>
          <b>人分</b>
        </div>
        <%= render 'recipe_ingredients_fields', f: recipe %>
      </div>
    </div>

    <h4>作り方</h4>
    <hr>
    <div class="row">
      <div class="form-group col-sm-10">
        <%= render 'recipe_procedures_fields', f: recipe %>
      </div>
    </div>
    <hr>

    <div class="row select-row justify-content-end">
      <div class="form-group">
        <%= recipe.select :public_view, {'公開する': 0, '下書き': 1}, {}, class: 'form-control' %>
      </div>
    </div>

    <div class="row submit-row d-flex justify-content-end">
      <div class="actions">
        <%= recipe.submit 'レシピ作成', class: 'btn btn-success' %>
      </div>
    </div>

  <% end %>
</div>


<script>
  $(document).on('change', 'input[type=file]', function (e) {
    var str = $(this).siblings('.image-label');
    var reader = new FileReader();

    reader.onload = function (e) {
        $(str).find('.preview-recipe-image').attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
  });
</script>

app/views/recipes/show.html.erb
<div class="recipe-show rounded">



  <div class="d-flex justify-content-end">
    <div class="my-box w-25">

      <% if @recipe.favorited_by?(current_user) %>
        <%= link_to recipe_favorite_recipes_path(@recipe), method: :delete, class: 'p-2 text-muted' do %>
          <i class="fas fa-star" aria-hidden="true" style="color: red;"></i>
        <% end %>
      <% else %>
        <%= link_to recipe_favorite_recipes_path(@recipe), method: :post, class: 'p-2 text-muted' do %>
          <i class="far fa-star" aria-hidden="true"></i>
        <% end %>
      <% end %>

    </div>
    <% if user_signed_in? && @recipe.user.id == current_user.id %>
      <div class="my-box w-25">
        <%= link_to "編集", edit_recipe_path(@recipe), class: "p-2 text-muted" %>
      </div>
    <% end %>
    <div class="my-box w-25">
      <%= form_for @menu do |menu| %>
        <%= menu.hidden_field :recipe_id, value: @recipe.id %>
        <%= menu.select :servings_for, [['1',1],['2',2],['3',3],['4',4],['5',5]], class: "form-control" %> 人分
        <%= menu.submit '作る', class: "btn btn-outline-warning" %>
      <% end %>
    </div>
  </div>

  <div class="row headline">
    <h3 class="col-sm-9"><%= @recipe.title %></h3>
    <p class="text-right col-sm-3"> - <%= @recipe.user.name %></p>
  </div>

  <div class="row">
    <p class="col-sm-9"><%= @recipe.description %></p>
    <p class="text-right col-sm-3"><%= "約 #{@recipe.cooking_time} 分"%></p>
    <div class="recipe-image col-sm-6">
      <%= attachment_image_tag @recipe, :image %>
    </div>
    <div class="col-sm-5">
      <h4>材料</h4>
      <p>　<%= @recipe.servings_for %>人分</p>
      <table class="table table-sm">
        <% @recipe.recipe_ingredients.each do |ingredient| %>
          <tr>
            <td>・<%= ingredient.ingredient.name %></td>
            <td>
              <%= ingredient.quantity %>
              <%= "（#{ingredient.gram}g）" if ingredient.gram? %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row row-procedure">
    <h4>作り方</h4>
    <table class="table table-procedure">
      <% if @recipe %>
        <% @recipe.recipe_procedures.each.with_index(1) do |procedure, i| %>
          <tr>
            <td><%= i %></td>
            <td><%= procedure.instruction %></td>
            <%#= attachment_image_tag procedure.object, :image if procedure.object.image %>
            <td><%= attachment_image_tag procedure, :image, class: 'procedure-image' if procedure.image %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>