config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: %i[show edit update] do
    get :menus, on: :collection
    get :favorite_recipes, on: :collection
    get :update_servings_for
  end

  resources :recipes do
    resource :favorite_recipes, only: %i[create destroy]
  end
  resources :categories # index, create
  resources :units
  resources :ingredients
  resources :user_ingredients
  resources :menus, only: %i[create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validation
  validates :name, presence: true, length: { maximum: 8 }
  has_many :recipes, dependent: :destroy
  has_many :recipes,          dependent: :destroy
  has_many :user_ingredients, dependent: :destroy
  has_many :menus,            dependent: :destroy
  has_many :favorite_recipes, dependent: :destroy
  has_many :recipes_through_favorite, through: :favorite_recipes, source: :recipe

  # validations
  validates :name, presence: true, uniqueness: true, length: { in: 3..8 }
  validates :servings_for,  presence: true,
                            numericality: {
                              only_integer: true,
                              greater_than_or_equal_to: 1
                            }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to current_user, success: '更新しました'
    else
      render 'show'
    end
  end

  def update_servings_for
    @user = User.find(current_user.id)
    if @user.update(servings_for: params[:servings_for])
      redirect_to current_user, success: '更新しました'
    else
      render 'show'
    end
  end

  def menus
    @menus = current_user.menus.includes(:recipe)
    render '/menus/index'
  end

  def favorite_recipes
    @favorite_recipes = current_user.recipes_through_favorite.includes(:user)
    render '/favorite_recipes/index'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :servings_for)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="user-page">
  <h3>登録情報</h3>
  <hr>
  <div class="container-fuild border">
    <div class="row">
      <div class="col-3">
        <div class="list-group" id="list-tab" role="tablist">
          <a class="list-group-item list-group-item-action active" id="tab-menu-1"
              data-toggle="list" href="#tab-content-1"
              role="tab" aria-controls="tab-content-1">プロフィール</a>
          <a class="list-group-item list-group-item-action" id="tab-menu-2"
              data-toggle="list" href="#tab-content-2"
              role="tab" aria-controls="tab-content-2">レシピ設定</a>
        </div>
      </div>
      <div class="col-9">
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="tab-content-1"
              role="tabpanel" aria-labelledby="tab-menu-1">
            <table class="table">
              <%= form_for @user do |f| %>
                <%= render 'layouts/error_messages', model: f.object %>
                <tr><th>ユーザー名</th><td><%= f.text_field :name, class: 'form-control' %></td></tr>
                <tr><th>メールアドレス</th><td><%= f.email_field :email, class: 'form-control' %></td></tr>
                <caption><%= f.submit "更新", class: 'btn btn-sm btn-outline-primary' %></caption>
              <% end %>
            </table>
          </div>
          <div class="tab-pane fade" id="tab-content-2"
              role="tabpanel" aria-labelledby="tab-menu-2">
              <table class="table">
                <tr>
                  <th>デフォルト人数分</th>
                  <td>
                    <%= form_tag user_update_servings_for_path(current_user), method: :get do %>
                      <div class="input-group mb-2">
                        <%= number_field_tag :servings_for, params[:servings_for], value: current_user.servings_for, class: 'form-control' %>
                          <div class="input-group-append">
                            <%= submit_tag '更新', class: 'btn btn-outline-secondary' %>
                          </div>
                      </div>
                    <% end %>
                  </td>
                </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>