config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: %i[show edit update] do
    get :menus, on: :collection
    get :favorite_recipes, on: :collection
    get :update_servings_for
  end

  resources :recipes do
    resource :favorite_recipes, only: %i[create destroy]
  end
  resources :categories # index, create
  resources :units
  resources :ingredients
  resources :user_ingredients
  resources :menus, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :user_ingredients,   dependent: :destroy

  # 該当なしの場合、作成してidを返すか,nilを返すか選択
  def self.get_id(name, new_create = false)
    ingredient = Ingredient.find_by(name: name)

    if ingredient.nil? && new_create
      ingredient = Ingredient.new(name: name)
      ingredient.save
    end
    ingredient.id
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :recipe_procedures,  dependent: :destroy
  has_many :recipe_ingredients, dependent: :destroy
  has_many :menu,               dependent: :destroy
  has_many :favorite_recipes,   dependent: :destroy

  accepts_nested_attributes_for :recipe_procedures,  allow_destroy: true
  accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true

  attachment :image

  # validations
  validates :title,  presence: true, length: { maximum: 10 }

  # TODO: 要テスト
  def self.get_ranking_from(from = Time.local(2000))
    Recipe.find(FavoriteRecipe.group(:recipe_id).where('created_at >= ?', from)
      .order('count(recipe_id) desc').limit(10).pluck(:recipe_id))
  end

  def favorited_by?(user)
    favorite_recipes.where(user_id: user.id).exists?
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  attr_accessor :name

  belongs_to :recipe
  belongs_to :ingredient
  belongs_to :unit
end

app/models/recipe_procedure.rb
class RecipeProcedure < ApplicationRecord
  belongs_to :recipe

  attachment :image
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :user_ingredients,   dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validation
  validates :name, presence: true, length: { maximum: 8 }
  has_many :recipes, dependent: :destroy
  has_many :recipes,          dependent: :destroy
  has_many :user_ingredients, dependent: :destroy
  has_many :menus,            dependent: :destroy
  has_many :favorite_recipes, dependent: :destroy
  has_many :recipes_through_favorite, through: :favorite_recipes, source: :recipe

  # validations
  validates :name, presence: true, uniqueness: true, length: { in: 3..8 }
  validates :servings_for,  presence: true,
                            numericality: {
                              only_integer: true,
                              greater_than_or_equal_to: 1
                            }
end

app/models/user_ingredient.rb
class UserIngredient < ApplicationRecord
  attr_accessor :name

  belongs_to :user
  belongs_to :ingredient
  belongs_to :unit
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.includes(:recipes)
                          .sort { |a, b| b.recipes.size <=> a.recipes.size }
    # TODO: ランキング表示
    @weekly_recipes  = Recipe.get_ranking_from(Time.current.beginning_of_week)
    @monthly_recipes = Recipe.get_ranking_from(Time.current.beginning_of_month)
    @total_recipes   = Recipe.get_ranking_from
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  
</footer>

app/views/layouts/_header.html.erb
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<header>
  <div class="header-links">
    <div class="logo">
      <%= link_to 'My Recipe', root_path %>
    </div>
  </div>

  <div class="header-search">
    <%#= search_field %>
    <form method="get" action="#" class="search_container">
      <input type="text" size="25" placeholder="料理名・食材名">
      <input type="submit" value="&#xf002">
    </form>
  </div>

  <div class="header-btn-items">
    <% if user_signed_in? %>

      <div class="header-btn">
        <%= link_to menus_users_path, class: 'btn' do %>
          <span class="fas fa-utensils icon"></span>
          <span class="btn-text">今日のごはん</span>
        <% end %>
      </div>

      <div class="header-btn">
        <%= link_to favorite_recipes_users_path, class: 'btn' do %>
          <span class="fas fa-star icon"></span>
          <span class="btn-text">お気に入り</span>
        <% end %>
      </div>

      <div class="header-btn">
        <%= link_to new_recipe_path, class: 'btn' do %>
          <span class="fas fa-edit icon"></span>
          <span class="btn-text">レシピ投稿</span>
        <% end %>
      </div>

      <div class="dropdown header-btn">
        <a class="btn" href="#" role="button" id="dropdownMenuLink" aria-haspopup="true" aria-expanded="false">
            <span class="fas fa-user icon"></span>
            <span class="btn-text"><%= current_user.name %></span>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
          <%= link_to '設定', current_user, class: 'dropdown-item' %>
          <%= link_to '自宅の材料', user_ingredients_path, class: 'dropdown-item' %>
          <%= link_to '材料一覧', ingredients_path, class: 'dropdown-item' %>
          <%= link_to 'レシピ一覧', recipes_path, class: 'dropdown-item' %>
          <%= link_to 'カテゴリー', categories_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, "data-confirm" => "本当にログアウトしますか？", class: 'dropdown-item' %>
        </div>
      </div>

    <% else %>

      <div class="header-btn">
        <%= link_to new_user_session_path, class: 'btn' do %>
          <span class="fas fa-sign-in-alt icon"></span>
          <span class="btn-text">ログイン</span>
        <% end %>
      </div>

      <div class="header-btn">
        <%= link_to new_user_registration_path, class: 'btn' do %>
          <span class="fas fa-user icon"></span>
          <span class="btn-text">ユーザー登録</span>
        <% end %>
      </div>

      <div class="header-btn">
        <%= link_to new_user_registration_path, class: 'btn' do %>
          <span class="fas fa-book-reader icon"></span>
          <span class="btn-text">初めての方へ</span>
        <% end %>
      </div>

    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- font -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
      <% message_type = 'danger'  if message_type == 'alert' %>
      <% message_type = 'success' if message_type == 'notice' %>
      <div class= "<%= "alert alert-#{message_type} alert-dismissible" %>" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>

    <!-- bootstrap -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  </body>
</html>